pipeline {
    environment {
        BRANCH = "${env.GIT_BRANCH}"
        registryCredential = 'DOCKER-HUB-ACCESS'
        imageFastAPI = "krishangopal/$JOB_NAME-fastapi"

    }

    agent any

    stages {
        stage('build') {
            steps {
	       script {
                  image = docker.build( imageFastAPI + ":$BUILD_NUMBER", '-f fastapi/Dockerfile .')
	       }
            }
        }

	stage('push') {
            steps {
	       script {
                   docker.withRegistry( '', registryCredential ) {
		      image.push('latest')
                   }
	       }
            }
        }

	stage('run') {
            steps {
	       script {
                  docker.image(imageFastAPI).run("--name $JOB_NAME-fastapi")
	       }
            }
        }
    }

}