version: '3'
services:
  jenkins:
   build: .
   container_name: jenkins
   privileged: true
   restart: always
   ports:
    - 8001:8080
   volumes:
    - jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker

  registry:
   image: registry
   container_name: registry
   restart: always
   ports:
    - 5000:5000
 
volumes:
  jenkins:
    external: false
